# Generated by Django 4.0.1 on 2022-01-25 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children_books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='email',
            field=models.EmailField(default='rc@gmail.com', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='author',
            name='first_name',
            field=models.CharField(default='jdd', max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='author',
            name='last_name',
            field=models.CharField(default='ree', max_length=30),
            preserve_default=False,
        ),
    ]
