# Generated by Django 4.0.1 on 2022-01-11 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('children_books', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Author',
        ),
    ]
