# Generated by Django 4.0.1 on 2022-01-24 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children_books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='user',
        ),
        migrations.AddField(
            model_name='author',
            name='email',
            field=models.EmailField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='first_name',
            field=models.CharField(default='test', max_length=25, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='author',
            name='last_name',
            field=models.CharField(default='user_3', max_length=25, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='author',
            name='pen_name',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
