# Generated by Django 4.0.1 on 2022-01-11 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children_books', '0002_rename_user_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
