# Generated by Django 4.0.1 on 2022-01-11 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('children_books', '0003_book_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_upload', models.ImageField(upload_to='pages')),
                ('page_number', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='children_books.author')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='children_books.book')),
            ],
        ),
    ]
