# Generated by Django 4.0.1 on 2022-01-11 19:45

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children_books', '0004_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='img_upload',
            field=models.ImageField(upload_to=django.core.files.storage.FileSystemStorage(location='/media/photos')),
        ),
    ]
