# Generated by Django 4.0.1 on 2022-01-11 19:47

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('children_books', '0005_alter_page_img_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='img_upload',
            field=models.ImageField(storage=django.core.files.storage.FileSystemStorage(location='/media/photos'), upload_to=''),
        ),
    ]
